# Generated by Django 3.0.3 on 2020-02-05 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('number', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('ru', models.TextField(verbose_name='Текст на русском')),
                ('uz', models.TextField(verbose_name='Текст на узбекском')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='PaySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('token', models.CharField(max_length=256, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Платежная система',
                'verbose_name_plural': 'Платежные системы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=256, verbose_name='Название на русском')),
                ('uz', models.CharField(max_length=256, verbose_name='Название на узбекском')),
                ('ruDescription', models.TextField(max_length=256, verbose_name='Описание на русском')),
                ('uzDescription', models.TextField(max_length=256, verbose_name='Описание на узбекском')),
                ('photo', models.ImageField(upload_to='media/common/', verbose_name='Фото')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramId', models.PositiveIntegerField(verbose_name='ID Telegram')),
                ('phone', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('username', models.CharField(max_length=256, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('token', models.CharField(max_length=256, verbose_name='Токен бота')),
                ('paySystem', models.ManyToManyField(to='bot.PaySystem')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Cart')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=256, verbose_name='Название на русском')),
                ('uz', models.CharField(max_length=256, verbose_name='Название на узбекском')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('photo', models.ImageField(upload_to='media/common/', verbose_name='Фото')),
                ('products', models.ManyToManyField(to='bot.Product')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='bot.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TelegramUser'),
        ),
    ]
