# Generated by Django 2.2.3 on 2020-02-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200206_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoUrl', models.CharField(max_length=512, verbose_name='url')),
                ('fileId', models.IntegerField(blank=True, null=True, verbose_name='fileId')),
            ],
        ),
    ]
