# Generated by Django 2.2.3 on 2020-02-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='fileId',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='fileId'),
        ),
    ]
