# Generated by Django 2.2.3 on 2020-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Подтвержден'),
        ),
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.BooleanField(default=True, verbose_name='Оплачено наличными'),
        ),
        migrations.AddField(
            model_name='order',
            name='click',
            field=models.BooleanField(default=True, verbose_name='Оплачено Click'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='order',
            name='geoX',
            field=models.IntegerField(blank=True, null=True, verbose_name='Локация X'),
        ),
        migrations.AddField(
            model_name='order',
            name='geoY',
            field=models.IntegerField(blank=True, null=True, verbose_name='Локация X'),
        ),
        migrations.AddField(
            model_name='order',
            name='payMe',
            field=models.BooleanField(default=True, verbose_name='Оплачено PayMe'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(default=None, max_length=256, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
