# Generated by Django 2.2.3 on 2020-02-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200208_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actevated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения заказа'),
        ),
    ]
