# Generated by Django 2.2.3 on 2020-02-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='actevated',
            new_name='activated',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='readlName',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя в телеграм'),
        ),
    ]
