# Generated by Django 2.2.3 on 2020-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20200209_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Доставка'),
        ),
    ]
