# Generated by Django 2.2.3 on 2020-02-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20200209_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='readlName',
            new_name='realName',
        ),
    ]
