# Generated by Django 2.2.3 on 2020-02-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20200209_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='Оплачено наличными'),
        ),
        migrations.AlterField(
            model_name='order',
            name='click',
            field=models.BooleanField(default=False, verbose_name='Оплачено Click'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payMe',
            field=models.BooleanField(default=False, verbose_name='Оплачено PayMe'),
        ),
    ]
